### ISSUE TITLE
Artikelcode wird in der Artikelansicht nicht angezeigt

### ISSUE THREAD

**Issue by vic-t** [vic-t/erpitst#2]
In der Artikelansicht steht in der Titelzeile immer der Artikelname. Der Artikelcode wird erst mit einem Klick auf die Titelzeile angezeigt. Kann man das anders einstellen?

**Comment by lasalesi** [comment]
In der Formularansicht ist der Artikelcode oben rechts (grau), ausser er ist identisch mit dem Artikelnamen. 

In der Listenansicht der Artikel ist der Artikelcode in der rechten Spalte (ausser identisch mit dem Artikelname, dann ausgeblendet)
