### ISSUE TITLE
Standard-MWST-Vorlage wird bei Rechnungserstellung aus Projekt nicht hinterlegt

### ISSUE THREAD

**Issue by vic-t** [vic-t/erpitst#4]
Wenn vom Kunden aus eine Rechnung generiert wird, wird die als Standard hinterlegte Vorlage für Verkaufssteuern automatisch hinterlegt. Bei der Erstellung einer Rechnung von einem Projekt aus geschieht dies nicht.

**Comment by lasalesi** [comment]
Gelöst mit #5
