### ISSUE TITLE
Fehlende Verknüpfung zum Kunden bei Rechnungsstellung von Projekt aus

### ISSUE THREAD

**Issue by vic-t** [vic-t/erpitst#5]
Ein Projekt kann mit höchstens einem Kunden verknüpft sein. Wenn nun also von einem Projekt aus eine Rechnung erstellt wird, welches bereits mit einem Kunden verknüpft ist, sollte es nicht nötig sein, den Kunden zusätzlich auswählen zu müssen. Dieser sollte automatisch hinterlegt werden.

**Comment by lasalesi** [comment]
Gelöst mit einem Custom Script auf der Sales Invoice

        if ((frm.doc.__islocal) && (frm.doc.project) && (!frm.doc.customer)) {
            // fetch customer from project
            frappe.call({
                "method": "frappe.client.get",
                "args": {
                    "doctype": "Project",
                    "name": frm.doc.project
                },
                "callback": function(response) {
                    var project = response.message;
                    if (project.customer) {
                        cur_frm.set_value("customer", project.customer);
                        setTimeout(function () {
                            cur_frm.set_value("taxes_and_charges", "MWST (302) - ITST");
                        }, 1000);
                    } 
                }
            });
        }
